Refactor atop rapcom
zancas/protoenv pull request #46
Opened 2017-01-14 05:12 UTC by zancas

@dangle 
Fixes: #42 

This greatly simplifies the code.    Note I haven't created a `contain` cli utility.

2017-01-14 06:29 UTC, zancas commented
@dangle waddya think?

2017-01-14 07:13 UTC, dangle requested changes
Looks pretty good. Fix the return value on the subprocess call and look at that indentation, then I think it's ready.

2017-01-14 07:13 UTC, dangle commented on tox.ini
> +#lint: pep257
Why comment these out? Merges don't require a passing build yet, do they?

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +Usage: containenv [--verbose] [--debug <LEVEL>] ( init | help ) [<args>...]
If you take `[--log-level <level>]` as an option you get logging for free from rapcom.

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +Usage: containenv [--verbose] [--debug <LEVEL>] ( init | help ) [<args>...]
So this is only used in the case of `containenv help`?

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +_DEFAULT_DOC = __doc__.format("""Common containenv commands:
I'll try to get support for this into `rapcom` for 0.1.2.

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +    '''Usage: containenv init [metasource]
You should add an `Arguments` section to explain `[metasource]`.

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +    '''Usage: containenv activate [help]
Does this have weird indentation when you run `containenv activate -h`? I wouldn't expect `dedent` to do anything here.

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +    '''Usage: containenv activate [help]
What does `containenv activate help` do? The built in subcommand help is `containenv help activate`. Custom help message?

2017-01-14 07:13 UTC, dangle commented on containenv/commands/containenv.py
> +        subprocess.call(["bash", self.target])
This should return the result of `subprocess.call`.

2017-01-14 07:13 UTC, dangle commented on containenv/commands/test/test_containenv_init.py
These inline tests should be moved out of the packaged code.

2017-01-14 15:29 UTC, zancas commented on containenv/commands/test/test_containenv_init.py
Oh dear!   I disagree with this...   why exclude tests?

2017-01-14 21:38 UTC, zancas commented on tox.ini
> +#lint: pep257
uncommented

2017-01-15 04:31 UTC, zancas commented on containenv/commands/containenv.py
> +Usage: containenv [--verbose] [--debug <LEVEL>] ( init | help ) [<args>...]
`--verbose`excised.

2017-01-15 04:32 UTC, zancas commented on containenv/commands/containenv.py
> +Usage: containenv [--verbose] [--debug <LEVEL>] ( init | help ) [<args>...]
Removed, depends on the `rapcom` defaults for the primary command.

2017-01-15 04:33 UTC, zancas commented on containenv/commands/containenv.py
> +_DEFAULT_DOC = __doc__.format("""Common containenv commands:
Nice to have...   I think validation is much more important.

2017-01-15 04:40 UTC, zancas commented on containenv/commands/containenv.py
> +    '''Usage: containenv init [metasource]
Added.

2017-01-15 04:46 UTC, zancas commented on containenv/commands/containenv.py
> +    '''Usage: containenv activate [help]
It was indented...   I fixed it.

2017-01-15 04:47 UTC, zancas commented on containenv/commands/containenv.py
> +    '''Usage: containenv activate [help]
It's gone.

2017-01-15 05:03 UTC, zancas commented on containenv/commands/test/test_containenv_init.py
done

2017-01-15 05:08 UTC, zancas commented on containenv/commands/containenv.py
> +    '''Usage: containenv activate [help]
oops...  this breaks style checks...  and upon a moments reflection...   properly so...   I think rapcom has to handle this gracefully.

2017-01-15 06:34 UTC, dangle approved these changes

2017-01-15 06:34 UTC, merged